version: '2'

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile.prod
        environment:
            PORT: 80
            PRODUCTION: 'true'
        ports:
         - "80:80"